# Welcome to Jekyll!
permalink: /blog/:year/:month/:day/:title 
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chaos.Work
email: huangchao.cpp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  make life
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chaos.work" # the base hostname & protocol for your site
twitter_username: huangchao
github_username:  chaoswork

# Build settings
markdown: kramdown
exclude: ["*.org"]
